name: Docker Image CI

on: [workflow_dispatch]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Build the Nuxt app Docker image
      uses: actions/checkout@v3
      run: docker build . --file backend/Dockerfile --tag media-annotator-frontend:latest
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ruslantau/media-annotator-frontend:latest

  build-backend:
    runs-on: ubuntu-latest
    steps:
    - name: Build the FastAPI app Docker image
      uses: actions/checkout@v3
      run: docker build . --file backend/Dockerfile --tag media-annotator-backend:latest
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ruslantau/media-annotator-backend:latest
