name: Docker Image CI

on: [workflow_dispatch]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Get repo code
      uses: actions/checkout@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push image
      uses: docker/build-push-action@v4
      with:
        context: .
        tags: ruslantau/media-annotator-frontend:latest
        push: ${{ github.event_name != 'pull_request' }}

  build-backend:
    runs-on: ubuntu-latest
    steps:
    - name: Get repo code
      uses: actions/checkout@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ruslantau/media-annotator-backend:latest