name: Docker Image CI

on: [workflow_dispatch]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get repo code
      uses: actions/checkout@v3
      
    - name: Build image
      run: docker build . --file backend/Dockerfile --tag media-annotator-frontend:latest

    - name: Push image
      run: docker push ruslantau/media-annotator-frontend:latest


  build-backend:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get repo code
      uses: actions/checkout@v3
      
    - name: Build image
      run: docker build . --file backend/Dockerfile --tag media-annotator-backend:latest

    - name: Push image
      run: docker push ruslantau/media-annotator-backend:latest
