name: Docker Image CI

on: [push, workflow_dispatch]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Nuxt app Docker image
      run: docker build . --file backend/Dockerfile --tag media-annotator-frontend:latest

  build-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the FastAPI app Docker image
      run: docker build . --file backend/Dockerfile --tag media-annotator-backend:latest
